[project]
name = "loxsa-patch2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8.18"
dependencies = [
    "matplotlib>=3.7.5",
    "scikit-learn>=1.3.2",
    "seaborn>=0.13.2",
    "streamlit>=1.40.1",
    "tensorflow>=2.13.1",
]
